mysite/myauth/urls.py
from django.urls import path


from .views import (
    AccountView,
    AboutMeView,
    RegisterView,
    login_view,
    logout_view,
    ProfileUpdateView,
    AllProfilesView,
    ProfileInfoView,
    ProfileInfoUpdateView,
)

app_name = "myauth"

urlpatterns = [
    path("", AccountView.as_view(), name="accounts"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("registration/", RegisterView.as_view(), name="registration"),
    path("about-me/", AboutMeView.as_view(), name="about-me"),
    path("about-me/<int:pk>/update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("profiles/", AllProfilesView.as_view(), name="profiles"),
    path("profiles/<int:pk>/info/", ProfileInfoView.as_view(), name="profiles-info"),
    path("profiles/<int:pk>/info/update/", ProfileInfoUpdateView.as_view(), name="profiles-info-update"),
]

mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('admin/', admin.site.urls, name='admin'),
    path('shop/', include('shopapp.urls'), name='shop'),
    path('accounts/', include('myauth.urls'), name='myauth'),
]

if settings.DEBUG:
    urlpatterns.extend(
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    )

    urlpatterns.extend(
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    )

mysite/shopapp/urls.py
from django.urls import path

from .views import (
    ShopIndexView,
    ProductDetailsView,
    ProductsListView,
    OrdersListView,
    OrderDetailView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
    UserOrdersListView,
    UserOrdersListExport,
)

app_name = "shopapp"

urlpatterns = [
    path("", ShopIndexView.as_view(), name="index"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/<int:pk>/", ProductDetailsView.as_view(), name="product_details"),
    path("products/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/archive/", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/user/<int:user_id>/", UserOrdersListView.as_view(), name="user_orders"),
    path("orders/user/<int:user_id>/export/", UserOrdersListExport.as_view(), name="user_orders_export"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_details"),
]

mysite/shopapp/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    class Meta:
        ordering = ["name", "price"]

    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"


class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name="orders")

mysite/shopapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.cache import cache
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, reverse, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Product, Order
from .serializers import OrderSerializer


class ShopIndexView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest) -> HttpResponse:
        context = {}
        return render(request, "shopapp/shop-index.html", context=context)


class ProductDetailsView(PermissionRequiredMixin, DetailView):
    permission_required = ["shopapp.view_product"]
    template_name = "shopapp/products-details.html"
    model = Product
    context_object_name = "product"


class ProductsListView(PermissionRequiredMixin, ListView):
    permission_required = ["shopapp.view_product"]
    ordering = ["pk",]
    template_name = "shopapp/products-list.html"
    context_object_name = "products"
    queryset = Product.objects.filter(archived=False)


class ProductCreateView(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ["shopapp.add_product", ]
    model = Product
    fields = "name", "price", "description", "discount"
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        form.instance.created_by = self.request._cached_user
        response = super().form_valid(form)
        return response


class ProductUpdateView(PermissionRequiredMixin, LoginRequiredMixin, UpdateView):
    permission_required = ["shopapp.change_product", ]
    model = Product
    fields = "name", "price", "description", "discount"
    template_name_suffix = "_update_form"

    def get_success_url(self):
        return reverse(
            "shopapp:product_details",
            kwargs={"pk": self.object.pk},
        )


class ProductDeleteView(PermissionRequiredMixin, LoginRequiredMixin, DeleteView):
    permission_required = ["shopapp.delete_product", ]
    model = Product
    success_url = reverse_lazy("shopapp:products_list")

    def form_valid(self, form):
        success_url = self.get_success_url()
        self.object.archived = True
        self.object.save()
        return HttpResponseRedirect(success_url)


class UserOrdersListView(LoginRequiredMixin, ListView):
    template_name = "shopapp/user_orders_list.html"
    context_object_name = "orders"

    def get_success_url(self):
        return reverse(
            "shopapp:user_orders",
            kwargs={"user_id": self.request.user.id},
        )

    def get_queryset(self):
        self.owner = get_object_or_404(User, pk=self.kwargs.get("user_id"))
        return Order.objects.filter(user=self.owner)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context.update(
            {
                "owner": self.owner,
            }
        )
        return context


class UserOrdersListExport(LoginRequiredMixin, View):
    def get(self, request: HttpRequest, **kwargs) -> JsonResponse:
        self.owner = get_object_or_404(User, pk=kwargs.get("user_id"))
        cache_key = f"user_orders_export_{self.owner}"
        orders_data = cache.get(cache_key)
        if orders_data is None:
            user_orders = Order.objects.filter(user=self.owner).order_by("pk")
            orders_data = OrderSerializer(user_orders, many=True).data
            cache.set(cache_key, orders_data, 300)
        return JsonResponse({"orders": orders_data})


class OrdersListView(PermissionRequiredMixin, LoginRequiredMixin, ListView):
    permission_required = ["shopapp.view_order", ]
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )


class OrderDetailView(PermissionRequiredMixin, LoginRequiredMixin, DetailView):
    permission_required = ["shopapp.view_order", ]
    queryset = (
        Order.objects
        .select_related("user")
        .prefetch_related("products")
    )

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock %}
  </title>
  <style>
    {% block style %}
    {% endblock %}
  </style>
</head>
<body>

{% block body %}
  Base body
{% endblock %}

</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Groups List
{% endblock %}

{% block body %}
  <h1>Groups:</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
  {% if not groups %}
    <h3>No groups yet</h3>
  {% else %}
    <ul>

      {% for group in groups %}
          <li>
            <div>{{ group.name }}</div>
            <ul>
              {% for permission in group.permissions.all %}
                <li>
                  {{ permission.name }}
                  (<code>{{ permission.codename }}</code>)
                </li>
              {% endfor %}

            </ul>
          </li>
      {% endfor %}

    </ul>
  {% endif %}
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_detail.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Order #{{ object.pk }} details
{% endblock %}

{% block body %}
  <h1>Order #{{ object.pk }}</h1>
  <div>
    <p>Order by {% firstof object.user.first_name object.user.username %}</p>
    <p>Promocode: <code>{{ object.promocode }}</code></p>
    <p>Delivery address: {{ object.delivery_address }}</p>
    <div>
      Product in order:
      <ul>
        {% for product in object.products.all %}
          <li>{{ product.name }} for ${{ product.price }}</li>
        {% endfor %}

      </ul>
    </div>
  </div>

  <div>
    <a href="{% url 'shopapp:orders_list' %}">Back to orders</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order_list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Orders list
{% endblock %}

{% block body %}
  <h1>Orders:</h1>
  {% if object_list %}
    <div>
      {% for order in object_list %}
        <div>
          <p><a href="{% url 'shopapp:order_details' pk=order.pk %}"
          >Details #{{ order.pk }}</a></p>
          <p>Order by {% firstof order.user.first_name order.user.username %}</p>
          <p>Promocode: <code>{{ order.promocode }}</code></p>
          <p>Delivery address: {{ order.delivery_address }}</p>
          <div>
            Product in order:
            <ul>
              {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
              {% endfor %}

            </ul>
          </div>

        </div>
      {% endfor %}

    </div>
  {% else %}
    <h3>No orders yet</h3>
  {% endif %}
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Confirm archive {{ object.name }}
{% endblock %}

{% block body %}
  <h1>Are you sure you want to archive {{ object.name }}?</h1>
  <br>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product</a>
  </div>
  <br>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Archive</button>
    </form>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create product
{% endblock %}

{% block body %}
  <h1>Create product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Create</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:products_list' %}"
    >Back to products list</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/product_update_form.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Update product
{% endblock %}

{% block body %}
  <h1>Update product</h1>
  <div>
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit">Update</button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:product_details' pk=object.pk %}"
    >Back to product #{{ object.pk }}</a>
  </div>
{% endblock %}

mysite/shopapp/templates/shopapp/products-details.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Product #{{ product.pk }}
{% endblock %}

{% block style %}
    * {          
        color: white;
        background-color: rgb(45, 0, 71);
    }

    .index {
        text-align: center;
    }

    .header-buttons {
        display: flex;
        justify-content: space-around;
        align-items: center;
    }

    .product-buttons {
      margin: 0 100px;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }

    .flexed-container {
        max-width: 1000px;
        height: 100%;
        margin-left: auto;
        margin-right: auto;
    }

    .custom-header > div {
        display: flex;
        justify-content: space-between;
    }

    .button-block {
        margin: 50px auto;
    }

    .button-block > div {
        padding: 20px;
        display: flex;
        flex-direction: column;
        justify-content: center;
    }
    
    .button-img {
        background-repeat: no-repeat;
        background-position-x: center;
        background-position-y: center;
    }

    .button-back {
      background-image: url('https://img.icons8.com/?size=100&id=98961&format=png&color=000000'); 
    }

    .button-home {
        background-image: url('https://img.icons8.com/?size=100&id=qBlNlefkEJPq&format=png&color=000000'); 
    }

    .button-update {
      background-image: url('https://img.icons8.com/?size=100&id=REaAov7RbGMN&format=png&color=000000'); 
    }

    .button-delete {
      background-image: url('https://img.icons8.com/?size=100&id=8112&format=png&color=000000'); 
    }

    button {
        font-size: 125%;
        border-radius: 25px;
        height: 160px;
        width: 200px;
        background-color: rgb(80, 0, 126);
    }

    button:hover {
        background-color: rgb(0, 94, 94);
        color: red;
    }

    button:focus {
        background-color: rgb(0, 94, 94);
        color: rgb(139, 0, 0);
    }

    .blank-div {
        margin-left: 10%;
    }

    .product-case {
      margin: 10px 0;
      text-align: center;
      font-size: 200%;
    }
{% endblock %}

{% block body %}
<div class="custom-header">
    <div class="flexed-container">
        <div class="blank-div"></div>
        <div class="index">
            <h1>Продукт <strong>{{ product.name }}</strong></h1>
        </div>
        <div class="header-buttons" style="width: 140px;">
            <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-back" onclick="window.location.href = 'http://176.124.214.97:8000/shop/products/';" title="Назад."></button>
            <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-home" onclick="window.location.href = 'http://176.124.214.97:8000/';"></button>
        </div>
    </div>
</div>
<hr>
<div class="button-block">
  <div class="flexed-container">
    <div class="product-case">Description: {{ product.description }}</div>
    <div class="product-case">Price: {{ product.price }}</div>
    <div class="product-case">Discount: {{ product.discount }}</div>
    <div class="product-case">Archived: {{ product.archived }}</div>
  </div>
  <div class="flexed-container">
      <div class="product-buttons">
        {% if user.username == product.created_by.username and perms.shopapp.change_product %}
            <button style="width: 100px; height: 100px; background-size: 75%;" class="button-img button-update" onclick="window.location.href = 'http://176.124.214.97:8000/shop/products/{{ product.pk }}/update/';" title="Обновить запись."></button>
        {% else %}
            <button style="width: 100px; height: 100px; background-size: 75%;" class="button-img button-update" onclick="alert('Отказано в доступе!')" title="Обновить запись."></button>
        {% endif %}
        <button style="width: 100px; height: 100px; background-size: 75%;" class="button-img button-delete" onclick="window.location.href = 'http://176.124.214.97:8000/shop/products/{{ product.pk }}/archive/';" title="Удалить запись."></button>
      </div>
  </div>
</div>
<hr>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Products list
{% endblock %}

{% block style %}
  * {
    color: white;
    background-color: rgb(45, 0, 71);
  }

  .index {
    text-align: center;
  }

  .flexed-container {
    max-width: 1000px;
    height: 100%;
    margin-left: auto;
    margin-right: auto;
  }

  .custom-header > div {
    display: flex;
    justify-content: space-between;
  }

  .header-buttons {
    display: flex;
    justify-content: space-around;
    align-items: center;
  }

  .button-block {
    margin: 50px auto;
  }

  .button-block > div {
    padding: 20px;
    display: flex;
    flex-direction: column;
    align-items: center;
  }

  .button-img {
    background-repeat: no-repeat;
    background-position-x: center;
    background-position-y: center;
  }

  .button-back {
    background-image: url('https://img.icons8.com/?size=100&id=98961&format=png&color=000000'); 
  }

  .button-home {
    background-image: url('https://img.icons8.com/?size=100&id=qBlNlefkEJPq&format=png&color=000000'); 
  }

  .button-create {
    background-image: url('https://img.icons8.com/?size=100&id=avvbNhAwFDaX&format=png&color=000000'); 
  }

  button {
    font-size: 125%;
    border-radius: 25px;
    height: 160px;
    width: 200px;
    background-color: rgb(80, 0, 126);
  }

  button:hover {
    background-color: rgb(0, 94, 94);
    color: red;
  }

  button:focus {
    background-color: rgb(0, 94, 94);
    color: rgb(139, 0, 0);
  }
  
  .product-case {
    background-color: rgb(80, 0, 126);
    border: 1px solid white;
    border-radius: 10px;
    padding: 10px 20px;
    margin: 10px 0; 
    width: 250px;
  }

  .product-case > p, p > a {
    background-color: rgb(80, 0, 126);
  }

  .blank-div {
    margin-left: 15%;
  }
{% endblock %}
{% block body %}
<div class="custom-header">
  <div class="flexed-container">
      <div class="blank-div"></div>
      <div class="index">
          <h1>Продукты</h1>
      </div>
      <div class="header-buttons" style="width: 180px;">
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-back" onclick="window.location.href = 'http://176.124.214.97:8000/shop/';" title="Назад."></button>
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-home" onclick="window.location.href = 'http://176.124.214.97:8000/';" title="Главная страница."></button>
        {% if perms.shopapp.add_product %}
          <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-create" onclick="window.location.href = 'http://176.124.214.97:8000/shop/products/create/';" title="Создать продукт."></button>
        {% else %}
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-create" onclick="alert('Отказано в доступе!')" title="Создать продукт."></button>
        {% endif %}
      </div>
  </div>
</div>
<hr>
<div class="button-block">
  <div class="flexed-container">
    {% if products %}
    {% for product in products %}
      <div class="product-case">
        <p>Продукт №{{ product.pk }}</p>
        <hr>
        <p>Название: <a href="{% url 'shopapp:product_details' pk=product.pk %}">{{ product.name }}</a></p>
        <p>Цена: {{ product.price }} $.</p>
        <p>Скидка: {% firstof product.discount 'no discount' %} %.</p>
        <p>Создатель: {% firstof product.created_by 'NULL' %}.</p>
      </div>
    {% endfor %}
    {% else %}
      <h3>No products yet</h3>
    {% endif %}
  </div>  
</div>
<hr>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Shop Index
{% endblock %}

{% block style %}
  * {
    color: white;
    background-color: rgb(45, 0, 71);
  }

  .index {
    text-align: center;
  }

  .flexed-container {
    max-width: 1000px;
    height: 100%;
    margin-left: auto;
    margin-right: auto;
  }

  
  .header-buttons {
    display: flex;
    justify-content: space-around;
    align-items: center;
  }

  .button-block {
    margin: 50px auto;
  }

  .custom-header > div {
    display: flex;
    justify-content: space-between;
  }

  .button-block > div {
    padding: 20px;
    display: flex;
    justify-content: space-between;
  }

  .button-img {
    background-repeat: no-repeat;
    background-position-x: center;
    background-position-y: center;
  }

  .button-products {
    background-image: url('https://img.icons8.com/?size=100&id=yFMVbAeT4lMU&format=png&color=000000'); 
  }

  .button-orders {
    background-image: url('https://img.icons8.com/?size=100&id=UWsL0In9hUI3&format=png&color=000000'); 
  }

  .button-home {
    background-image: url('https://img.icons8.com/?size=100&id=qBlNlefkEJPq&format=png&color=000000'); 
  }

  button {
    font-size: 125%;
    border-radius: 25px;
    height: 160px;
    width: 200px;
    background-color: rgb(80, 0, 126);
  }

  button:hover {
    background-color: rgb(0, 94, 94);
    color: red;
  }

  button:focus {
    background-color: rgb(0, 94, 94);
    color: rgb(139, 0, 0);
  }

  .blank-div {
    margin-left: 5%;
  }
{% endblock %}
{% block body %}
<div class="custom-header">
  <div class="flexed-container">
      <div class="blank-div"></div>
      <div class="index">
          <h1>Магазин</h1>
      </div>
      <div class="header-buttons">
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-home" onclick="window.location.href = 'http://176.124.214.97:8000/';"></button>
    </div>
  </div>
</div>
<hr>
<div class="button-block">
  <div class="flexed-container">
      <div style="margin-left: 15%;">
          <button class="button-img button-products" onclick="window.location.href = 'http://176.124.214.97:8000/shop/products/';">
              Продукты
          </button>
      </div>
      <div style="margin-right: 15%;">
          <button class="button-img button-orders" onclick="window.location.href = 'http://176.124.214.97:8000/shop/orders/';">
              Заказы
          </button>
      </div>
  </div>  
</div>
<hr>

{% endblock %}

mysite/shopapp/templates/shopapp/user_orders_list.html
{% extends 'shopapp/base.html' %}

{% load cache %}

{% block title %}
  Orders list
{% endblock %}

{% block style %}
  * {
    color: white;
    background-color: rgb(45, 0, 71);
  }

  .index {
    text-align: center;
  }

  .flexed-container {
    max-width: 1000px;
    height: 100%;
    margin-left: auto;
    margin-right: auto;
  }

  .custom-header > div {
    display: flex;
    justify-content: space-between;
  }

  .header-buttons {
    display: flex;
    justify-content: space-around;
    align-items: center;
  }

  .button-block {
    margin: 20px auto;
  }

  .button-block > div {
    padding: 20px;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-around;
  }

  .button-img {
    background-repeat: no-repeat;
    background-position-x: center;
    background-position-y: center;
  }

  .button-back {
    background-image: url('https://img.icons8.com/?size=100&id=98961&format=png&color=000000'); 
  }

  .button-home {
    background-image: url('https://img.icons8.com/?size=100&id=qBlNlefkEJPq&format=png&color=000000'); 
  }

  .button-create {
    background-image: url('https://img.icons8.com/?size=100&id=avvbNhAwFDaX&format=png&color=000000'); 
  }

  button {
    font-size: 125%;
    border-radius: 25px;
    height: 160px;
    width: 200px;
    background-color: rgb(80, 0, 126);
  }

  button:hover {
    background-color: rgb(0, 94, 94);
    color: red;
  }

  button:focus {
    background-color: rgb(0, 94, 94);
    color: rgb(139, 0, 0);
  }
  
  .order-case {
    background-color: rgb(80, 0, 126);
    border: 1px solid white;
    border-radius: 10px;
    padding: 10px 20px;
    margin: 20px 0; 
    width: 250px;
  }

  .order-case > p, p > a, ul, li {
    background-color: rgb(80, 0, 126);
  }

  .blank-div {
    margin-left: 15%;
  }
{% endblock %}
{% block body %}
<div class="custom-header">
  <div class="flexed-container">
      <div class="blank-div"></div>
      <div class="index">
          <h1>Orders for user {{ owner.username }}</h1>
      </div>
      <div class="header-buttons" style="width: 180px;">
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-back" onclick="window.location.href = 'http://176.124.214.97:8000/shop/';" title="Назад."></button>
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-home" onclick="window.location.href = 'http://176.124.214.97:8000/';" title="Главная страница."></button>
        {% if perms.shopapp.add_product %}
          <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-create" onclick="window.location.href = 'http://176.124.214.97:8000/shop/products/create/';" title="Создать продукт."></button>
        {% else %}
        <button style="width: 50px; height: 50px; background-size: 75%;" class="button-img button-create" onclick="alert('Отказано в доступе!')" title="Создать продукт."></button>
        {% endif %}
      </div>
  </div>
</div>
<hr>
<div class="button-block">
  <div class="flexed-container">
    {% if orders %}
        {% for order in orders %}
        <div class="order-case">
            <p>Order №{{ order.pk }}</p>
            <hr>
            <p>delivery_address: {{ order.delivery_address }}</p>
            <p>promocode: {{ order.promocode }}</p>
            <p>created_at: {{ order.created_at }}</p>
            <hr>
            <p>products:</p>
            <ul>
                {% for product in order.products.all %}<li>{{ product.name }}</li>{% endfor %}
            </ul>
        </div>
        {% endfor %}
    {% else %}
      <h3>No orders yet</h3>
    {% endif %}
  </div>  
</div>
<hr>
{% endblock %}